config/routes.rb
RepoGit::Application.routes.draw do

  # Explicitly matching automatic favicon request, which otherwise will be matched below
  match 'favicon.ico' => proc { [404, {}, ['']] }

  match 'imprint' => 'holidays#imprint', as: :imprint

  match 'today' => 'holidays#index', as: :today

  match ':first/:second' => 'holidays#show', as: :holidays_two
  match ':first' => 'holidays#show', as: :holidays_one


  root :to => 'holidays#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/holidays_controller.rb
# coding: utf-8

# This is necessary as the holidays gem does some fancy stuff...
require 'holidays/de'

class HolidaysController < ApplicationController

  respond_to :html, :json

  before_filter :set_json_path

  def index
    @holidays = Holidays.on(Date.today, :de_)

    @requested_date = Date.today

    respond_with @holidays do |format|
      format.html { render 'index' }
    end
  end

  def show
    begin
      if params[:second]
        date = Date.parse params[:second]
        region = parse_region params[:first]
      else
        if params[:first]
          date = Date.parse params[:first] rescue nil
          region = parse_region params[:first] rescue nil

          if region.nil? && date.nil?
            raise ArgumentError
          end
        end

        date = Date.today if date.nil?
      end
    rescue
      render text: 'Bad request', status: :bad_request
      return
    end

    logger.debug({date: date, region: region}.to_s)

    lookup_region = region ? "de_#{region}".to_sym : :de_

    if Holidays::DE.defined_regions.include? lookup_region
      @holidays = Holidays.on(date, lookup_region)
    else
      @holidays = Holidays.on(date, :de_)

      unless lookup_region == :de_ || @holidays.any?{|h| h[:regions].include? :de}
        @holidays = []
      end
    end

    @requested_date = date
    @requested_region = region

    respond_with @holidays do |format|
      format.html { render 'index' }
    end
  end

  def imprint
  end

  private

  MAPPING = {
    'bw' => 'Baden-Württemberg',
    'by' => 'Bayern',
    'be' => 'Berlin',
    'bb' => 'Brandenburg',
    'hb' => 'Bremen',
    'hh' => 'Hamburg',
    'he' => 'Hessen',
    'mv' => 'Mecklenburg-Vorpommern',
    'ni' => 'Niedersachsen',
    'nw' => 'Nordrhein-Westfalen',
    'rp' => 'Rheinland-Pfalz',
    'sl' => 'Saarland',
    'sn' => 'Sachsen',
    'st' => 'Sachsen-Anhalt',
    'sh' => 'Schleswig-Holstein',
    'th' => 'Thüringen'
  }

  REVERSE = Hash[MAPPING.to_a.map{|m| [m[1].downcase, m[0]]}]

  def parse_region value
    sanitized = value.downcase

    region = sanitized if MAPPING.keys.include?(sanitized)

    region ||= REVERSE[sanitized]

    raise ArgumentError if region.nil?

    return region
  end

  def set_json_path
    if request.fullpath == '/' || request.fullpath == '/imprint'
      @json_path = today_path + '.json'
    else
      @json_path = request.fullpath + '.json'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/holidays/imprint.html.haml
%h2 Impressum
%p
  = link_to 'http://fortytools.com' do
    = image_tag 'ft.png'
%p
  fortytools gmbh

%p
  Volksdorfer Weg 60
  %br
  22393 Hamburg

%p
  info@fortytools.com

%p
  Amtsgericht Hamburg, Handelsregisternummer: HRB 115021
  %br
  Umsatzsteueridentifikationsnummer: DE-273620937

%h4 Vertretungsberechtigte Geschäftsführer:

%p
  Sebastian M. Gauck, Timo B. Kranz, Axel Tetzlaff
%p
  Inhaltlich verantwortlich gemäß § 6 MDStV: Timo B. Kranz

%h2 Datenschutzerklärung
%p
  Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“).
  Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert
  werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den
  Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an
  einen Server von Google in den USA übertragen und dort gespeichert.

%p
  Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse
  von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen
  Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur
  in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA
  übertragen und dort gekürzt. Die IP-Anonymisierung ist auf dieser Website aktiv. Im Auftrag
  des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung
  der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um
  weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber
  dem Websitebetreiber zu erbringen.

%p
  Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit
  anderen Daten von Google zusammengeführt. Sie können die Speicherung der Cookies durch eine
  entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf
  hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website
  vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das
  Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse)
  an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter
  dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren:
  = link_to 'http://tools.google.com/dlpage/gaoptout?hl=de', 'http://tools.google.com/dlpage/gaoptout?hl=de'

app/views/holidays/index.html.haml
- if @holidays.empty?

  %h1
    = t('.not')

    %small
      - if @requested_region.nil?
        = link_to t('.maybe_tomorrow'), holidays_one_path(first: @requested_date + 1.day)
      - else
        = link_to t('.maybe_tomorrow'), holidays_two_path(first: @requested_region, second: @requested_date + 1.day)

      - if @requested_region && @requested_region != 'by'
        = link_to t('.bavaria'), holidays_two_path(first: 'bayern', second: @requested_date)

- else

  %h1
    = t('.yeah')

    - if @holidays.any?{|h| h[:regions] != [:de]}
      %small= t('.only', regions: @holidays.first[:regions].map{|r| I18n.t(r)}.to_sentence)

app/views/layouts/_navigation.html.haml
%nav
  = link_to t('.home'), root_path
  |
  - if @json_path
    = link_to t('.api'), @json_path
    |
  = link_to t('.imprint'), imprint_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t('.title')

    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{name: "description", content: t('.description')}
    %meta{name: "keywords", content: t('.keywords')}

    = stylesheet_link_tag "application", media: "all"

    = csrf_meta_tags

%body
  %header
    = render "layouts/navigation"

  %section
    = yield

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39935103-1']);
  _gaq.push(['_setDomainName', 'feiertag.in']);
  _gaq.push(['_gat._anonymizeIp']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();